import Header from "@/components/Header"
import "./globals.css";
import "./page.module.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AppWalletProvider from "@/components/AppWalletProvider"
import { Provider } from "jotai"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "DeezQuest Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <AppWalletProvider>
            <Header />
            {children}
          </AppWalletProvider>
        </Provider>
      </body>
    </html>
  )
}
